### ISSUE TITLE
Tanstack Router로 인한 배포 환경 문제

### ISSUE THREAD

**Issue by algoORgoal** [uxplorerss/uxplorers-frontend#18]
- [ ] 배포 에서 Tanstack Router Devtools 렌더링되지 않게 하기
- [ ] baseurl `/uxplorers-frontend`로 지정하여 url에 repository name 포함시키기

**Comment by Turtle-Hwan** [comment]
@algoORgoal 
두 번째 이슈에 관해,

https://tanstack.com/router/v1/docs/framework/react/api/router/RouterOptionsType#basepath-property

basePath 속성이 있네요 참고하시면 좋을듯해서 올려요
