### ISSUE TITLE
Global State type, function 논의

### ISSUE THREAD

**Issue by Turtle-Hwan** [uxplorerss/uxplorers-frontend#46]
- useSearchQueryStore : 유저가 선택한 출발 터미널, 도착 터미널, 출발일시, 왕복 일시
 
- useTowardBusListStore : 가는 날 버스 정보

 
- useBackwardBusListStore : 오는 날 버스 정보

- useTicketListStore : 유저가 구매한 티켓 정보

**Comment by Turtle-Hwan** [comment]
@algoORgoal 
useSearchQuery 에서 현재 destDate 도착 날짜가 항상 현재 Date()로 되어 있는데,

유저가 편도로 선택할수도 있어서 Date() | null 로 두고 기본값을 null로 넣는 것이 더 나을 거 같습니다

어떻게 생각하시나요?

**Comment by Turtle-Hwan** [comment]
@algoORgoal 
useSearchQuery 에서 현재 destDate 도착 날짜가 항상 현재 Date()로 되어 있는데,

유저가 편도로 선택할수도 있어서 Date() | null 로 두고 기본값을 null로 넣는 것이 더 나을 거 같습니다

어떻게 생각하시나요?

**Comment by algoORgoal** [comment]
@Turtle-Hwan 그냥 undefined로 하는 건 이상한가요?

**Comment by Turtle-Hwan** [comment]
> @Turtle-Hwan 그냥 undefined로 하는 건 이상한가요?

초기값은 undefined로 해도 될 거 같아요
그런데 유저가 의도적으로 편도만 "선택" 했다는 것을 알리기 위해서 null이 더 나아보이기도 하네요

**Comment by algoORgoal** [comment]
초기값이랑 유저가 의도적으로 선택했다는 것을 구분할 이유가 있을까요?
일단 편도가 선택되지 않았을 때를 위한 상태가 필요하다는 것은 동의합니다.

**Comment by algoORgoal** [comment]
그러면 searchQuery에서 startDate property도 유저가 값을 안 넣었을 때는 undefined나 null을 넣어줘야 할 것 같아요.

**Comment by Turtle-Hwan** [comment]
아 저는 초기상태와 유저 선택 안함 상태를 동일하게 null로 두자는 말이었습니다!

시작 날짜는 현재 시각으로 두는 게 맞다고 생각하는 게, 시작 날짜도 없으면 표를 사는 의미가 없다고 생각합니다

그리고 시작 날짜는 무조건 선택하도록 제한해야 한다고 생각합니다

**Comment by algoORgoal** [comment]
아 좋은 거 같습니다. 
의도적으로 값이 없다는 상태를 나타내야 하니까 null이 적당하겠네요
시작 날짜 기본값을 현재 시각으로 둔다면 null을 안 해도 될 것 같고 좋은 UX 맞는 것 같습니다..

**Comment by Turtle-Hwan** [comment]
좋아요좋아요~


아니 그나저나 github 모바일 앱에서 이슈 코멘트 달 때 이전에 단 걸 textarea에서 초기화를 안시켜주네요...??!
