### ISSUE TITLE
시연까지 남은 테스크 목록

### ISSUE THREAD

**Issue by algoORgoal** [uxplorerss/uxplorers-frontend#78]
## 전역
- [ ] background color에 gray3 적용하기 @YongChanCho 

## 예매 확인 페이지
- [ ] `예매할 내역을 확인하세요` 텍스트와 카드 사이의 간격 조정하기 @algoORgoal 
- [ ] checkbox 버튼으로 티켓 선택할 수 있게 만들기 @algoORgoal 
- [ ] 티켓 추가 버튼 @algoORgoal 
- [ ] 예매 확인 페이지 바텀시트로 변경 @algoORgoal 
- [ ] 결제수단 선택하는 곳에서 radio button 모양 제대로 잡기 @algoORgoal 
- [ ] 수정 버튼 눌렀을 때 버스 선택 페이지로 다시 돌아가기 @algoORgoal 

## 결제하기 페이지
- [ ] pending 상태의 ticket에 구매 제한 시간 걸어놓기 @algoORgoal 
- [ ] PrimaryCard toggle 가능하게 만들기(summary/detail 상태 전환) @algoORgoal 

## 내 티켓 페이지
- [ ] 구현하기 @Turtle-Hwan 

## 예매완료 페이지
-  [x] 5초 보여주고 난 이후 홈페이지로 이동 @YongChanCho (홈으로 이동하기 버튼 추가하여 해결하였음)

## 기타
- [x] 프로젝트 README로 문서화하기 @algoORgoal

**Comment by algoORgoal** [comment]
@YongChanCho  @Turtle-Hwan 그 외에 버스 리스트 페이지인가, 검색 페이지에서 시각적으로 뭉개진다고 한 컴포넌트에 대해서 서술해주실 수 있을까요?

**Comment by Turtle-Hwan** [comment]
> @YongChanCho  @Turtle-Hwan 그 외에 버스 리스트 페이지인가, 검색 페이지에서 시각적으로 뭉개진다고 한 컴포넌트에 대해서 서술해주실 수 있을까요?

뭉개진다고 한 컴포넌트가 있었나요??

버스 리스트에서는 딱히 없습니다

**Comment by YongChanCho** [comment]
> @YongChanCho @Turtle-Hwan 그 외에 버스 리스트 페이지인가, 검색 페이지에서 시각적으로 뭉개진다고 한 컴포넌트에 대해서 서술해주실 수 있을까요?

출발지 선택 후 도착지 인풋 컴포넌트가 뭉개졌었는데 다시 해보니 되더라구요 혹시 수정하셨었나요??

**Comment by Turtle-Hwan** [comment]
> > @YongChanCho @Turtle-Hwan 그 외에 버스 리스트 페이지인가, 검색 페이지에서 시각적으로 뭉개진다고 한 컴포넌트에 대해서 서술해주실 수 있을까요?
> 
> 출발지 선택 후 도착지 인풋 컴포넌트가 뭉개졌었는데 다시 해보니 되더라구요 혹시 수정하셨었나요??

아 이건 제가 수정했습니다 👍

**Comment by YongChanCho** [comment]
> > > @YongChanCho @Turtle-Hwan 그 외에 버스 리스트 페이지인가, 검색 페이지에서 시각적으로 뭉개진다고 한 컴포넌트에 대해서 서술해주실 수 있을까요?
> > 
> > 
> > 출발지 선택 후 도착지 인풋 컴포넌트가 뭉개졌었는데 다시 해보니 되더라구요 혹시 수정하셨었나요??
> 
> 아 이건 제가 수정했습니다 👍

아하 이외엔 이상한 점 없습니다:)

**Comment by algoORgoal** [comment]
@Turtle-Hwan @YongChanCho 일단 테스크 어사인 해드렸습니다:) 혹시 할 게 너무 많거나 적다면 말씀해주시길 바랍니다!
